# HTTPS config
server:
  port: 8443
  ssl.key-store: classpath:keystore.p12
  ssl.key-store-password: tomcat
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: tomcat

spring:
# i18n config
  messages:
    basename: i18n/messages
# Datasource config
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
# Thymeleaf config
  thymeleaf:
    cache: false
    enabled: true
# EhCache config
  cache:
    ehcache:
      config: classpath:ehcache.xml

# MyBatis cofig
mybatis: 
  config-location: classpath:mybatis-config.xml

# Auto pager plugin
pagehelper:
    helperDialect: mysql
    offsetAsPageNum: true
  
# Logger config
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    
