# HTTPS config
server:
  port: 80
#  port: 8443
#  ssl.key-store: classpath:keystore.p12
#  ssl.key-store-password: tomcat
#  ssl.keyStoreType: PKCS12
#  ssl.keyAlias: tomcat

spring:
# i18n config
  messages:
    basename: i18n/messages, i18n/codes, i18n/validators
# Datasource config
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
# Thymeleaf config
  thymeleaf:
    cache: true
    enabled: true
    mode: HTML
# EhCache config
  cache:
    ehcache:
      config: classpath:ehcache.xml
# HttpSession config
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
# Jackson config
  jackson:
    date-format: yyyy-MM-dd

# MyBatis cofig
mybatis: 
  config-location: classpath:mybatis-config.xml

# Auto pager plugin
pagehelper:
    helperDialect: mysql
    offsetAsPageNum: true
  
# Logger config
logging:
  config: classpath:log4j2-dev.yml
    
